[#124] 태그 TextInput 리덕스 및 로직 추가
dnd-side-project/dnd-7th-6-frontend pull request #125
Opened 2022-08-10 14:34 UTC by ShinJongUng

## Summary
- TagInput 로직 추가
- TagInput 리덕스, TagInput Data 리덕스 로직 추가

## Comments
- 로직만 한번 확인해주세요

https://user-images.githubusercontent.com/65454966/183928748-2903b9da-2e66-49aa-924e-1ef9f8cd16a3.mp4

2022-08-10 16:06 UTC, vgihan approved these changes
수고하셨습니다 ! tagData가 1 이상이고, TextInput이 비어 있을 때 backspace를 누르면 가장 최근에 생성된 태그가 삭제되는 기능을 만들 수 있을 것 같아요 !

2022-08-10 16:06 UTC, vgihan commented on src/components/ReviewTagInput/ReviewTagInput.tsx
> +  const keyword: string = useSelector((state: RootState) => state.mapReducer.tagKeyword);
keyword state는 redux store로 관리할 필요가 없을 것 같아요 ! 그냥 useState로 관리해도 될 것 같습니당

2022-08-10 16:06 UTC, vgihan commented on src/components/ReviewTagInput/ReviewTagInput.tsx
> +            {tagData !== [] ? (
tagData.length > 0 으로 비교하는 게 좋을 것 같아요 !

2022-08-11 00:14 UTC, ShinJongUng commented on src/components/ReviewTagInput/ReviewTagInput.tsx
> +  const keyword: string = useSelector((state: RootState) => state.mapReducer.tagKeyword);
그.. Flatlist에 api검색 한거 나오게 하려했는데 생각해보니 맵 검색창과 다르게 같은 올가니즘에 있어서 useState로 관리해도 문제 없을거같네요

2022-08-11 05:47 UTC, vgihan commented on src/components/ReviewTagInput/ReviewTagInput.tsx
> +  const keyword: string = useSelector((state: RootState) => state.mapReducer.tagKeyword);
아 생각해보니 keyword 연관 검색어 기능이 필요하군요 ! redux로 가는게 맞을 것 같습니다

2022-08-11 12:32 UTC, ShinJongUng commented on src/components/ReviewTagInput/ReviewTagInput.tsx
> +  const keyword: string = useSelector((state: RootState) => state.mapReducer.tagKeyword);
아 ㅋㅋㅋㅋ useState로 옮겼는데 커밋했으니 한번 확인 부탁드립니다 ㅋㅋㅋ ㅠㅠ

2022-08-11 13:21 UTC, vgihan commented on src/components/ReviewTagInput/ReviewTagInput.tsx
> +  const keyword: string = useSelector((state: RootState) => state.mapReducer.tagKeyword);
ㅋㅋㅋㅋㅋㅋㅋㅋ ㅜㅜㅜㅜㅜ 확인하겠습니다

2022-08-11 13:25 UTC, vgihan approved these changes
수고하셨습니다 ~! 머지해서 태그 부분 갖다 써도 될까용 ??

2022-08-11 13:25 UTC, vgihan commented on src/components/ReviewSearchList/ReviewSearchList.tsx
> +  inputWord;
inputWord 필요한 코드인가요 ??

2022-08-11 13:25 UTC, vgihan commented on src/querys/useGetSearchedTag.ts
> +  return useQuery(['search'], async () => await getSearchedTag(searchingWord), {
await 붙여도 결국 Promise를 리턴하기 때문에, () => getSearchedTag(searchingWord) 라고 수정할 수 있습니다 !

2022-08-11 13:26 UTC, vgihan requested changes

2022-08-11 13:26 UTC, vgihan commented on src/components/ReviewTagInput/ReviewTagInput.tsx
> +  const tagData: any = useSelector((state: RootState) => state.reviewReducer.tagData);
엇.. 재사용 컴포넌트에서 redux 참조가 일어나면, 제가 사용하기 좀 힘들 것 같아요 ㅜㅜ

2022-08-13 06:27 UTC, ShinJongUng commented on src/components/ReviewTagInput/ReviewTagInput.tsx
> +  const tagData: any = useSelector((state: RootState) => state.reviewReducer.tagData);
수정 했습니다!~ 검색한 리스트 눌렀을때 로직도 추가했어요!

2022-08-13 11:58 UTC, vgihan approved these changes

2022-08-13 11:58 UTC, merged